// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace MT32Editor.BDD.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class TimbreEditorFeature : object, global::Xunit.IClassFixture<TimbreEditorFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Timbre Editor", "    The timbre editor allows creating, editing and managing MT-32 timbres.\n    Bo" +
                "th WinForms and Avalonia UIs must provide the same editing capabilities.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "TimbreEditor.feature"
#line hidden
        
        public TimbreEditorFeature(TimbreEditorFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/TimbreEditor.feature.ndjson", 78);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Create a new audible timbre")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Create a new audible timbre")]
        public async global::System.Threading.Tasks.Task CreateANewAudibleTimbre()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Create a new audible timbre", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 5
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 7
        await testRunner.WhenAsync("I create a new audible timbre", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 8
        await testRunner.ThenAsync("the timbre should have a valid name", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 9
        await testRunner.AndAsync("the timbre should have 4 partials", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Set timbre name")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set timbre name")]
        public async global::System.Threading.Tasks.Task SetTimbreName()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set timbre name", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 11
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 12
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
        await testRunner.WhenAsync("I set the timbre name to \"TestBass\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 14
        await testRunner.ThenAsync("the timbre name should start with \"TestBass\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Change active partial")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Change active partial")]
        public async global::System.Threading.Tasks.Task ChangeActivePartial()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Change active partial", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 16
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
        await testRunner.WhenAsync("I select partial 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
        await testRunner.ThenAsync("the active partial should be 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Toggle partial mute status")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Toggle partial mute status")]
        public async global::System.Threading.Tasks.Task TogglePartialMuteStatus()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Toggle partial mute status", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 21
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
        await testRunner.WhenAsync("I mute partial 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
        await testRunner.ThenAsync("partial 1 should be muted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
        await testRunner.WhenAsync("I unmute partial 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 26
        await testRunner.ThenAsync("partial 1 should not be muted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Set partial structure")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set partial structure")]
        public async global::System.Threading.Tasks.Task SetPartialStructure()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set partial structure", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 28
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
        await testRunner.WhenAsync("I set structure 1-2 to 6", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 31
        await testRunner.ThenAsync("structure 1-2 should be 6", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Toggle sustain")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Toggle sustain")]
        public async global::System.Threading.Tasks.Task ToggleSustain()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Toggle sustain", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 33
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 34
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 35
        await testRunner.WhenAsync("I enable sustain", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 36
        await testRunner.ThenAsync("sustain should be enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 37
        await testRunner.WhenAsync("I disable sustain", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 38
        await testRunner.ThenAsync("sustain should be disabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Toggle pitch bend")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Toggle pitch bend")]
        public async global::System.Threading.Tasks.Task TogglePitchBend()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Toggle pitch bend", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 40
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 41
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 42
        await testRunner.WhenAsync("I enable pitch bend on partial 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
        await testRunner.ThenAsync("pitch bend on partial 0 should be enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 44
        await testRunner.WhenAsync("I disable pitch bend on partial 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 45
        await testRunner.ThenAsync("pitch bend on partial 0 should be disabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Undo and redo timbre changes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Undo and redo timbre changes")]
        public async global::System.Threading.Tasks.Task UndoAndRedoTimbreChanges()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Undo and redo timbre changes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 47
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 48
        await testRunner.GivenAsync("a new timbre editor is opened with history", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 49
        await testRunner.WhenAsync("I set the timbre name to \"Changed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
        await testRunner.AndAsync("I record the change in history", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
        await testRunner.ThenAsync("the timbre name should start with \"Changed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 52
        await testRunner.WhenAsync("I undo the last change", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
        await testRunner.ThenAsync("the timbre should be restored to original state", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
        await testRunner.WhenAsync("I redo the last change", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
        await testRunner.ThenAsync("the timbre name should start with \"Changed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Copy and paste partial")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Copy and paste partial")]
        public async global::System.Threading.Tasks.Task CopyAndPastePartial()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Copy and paste partial", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 57
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 59
        await testRunner.WhenAsync("I set a parameter on partial 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
        await testRunner.AndAsync("I copy partial 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
        await testRunner.AndAsync("I paste to partial 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 62
        await testRunner.ThenAsync("partial 1 should have the same parameter as partial 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Set pitch parameters")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set pitch parameters")]
        [global::Xunit.InlineDataAttribute("0", "48", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("1", "40", "10", new string[0])]
        [global::Xunit.InlineDataAttribute("2", "8", "11", new string[0])]
        public async global::System.Threading.Tasks.Task SetPitchParameters(string paramNo, string value, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("paramNo", paramNo);
            argumentsOfScenario.Add("value", value);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set pitch parameters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 64
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 65
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 66
        await testRunner.WhenAsync(string.Format("I set parameter {0} on partial 0 to {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 67
        await testRunner.ThenAsync(string.Format("parameter {0} on partial 0 should be {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Set LFO parameters")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set LFO parameters")]
        [global::Xunit.InlineDataAttribute("20", "50", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("21", "75", "13", new string[0])]
        [global::Xunit.InlineDataAttribute("22", "30", "14", new string[0])]
        public async global::System.Threading.Tasks.Task SetLFOParameters(string paramNo, string value, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("paramNo", paramNo);
            argumentsOfScenario.Add("value", value);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set LFO parameters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 75
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 76
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 77
        await testRunner.WhenAsync(string.Format("I set parameter {0} on partial 0 to {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 78
        await testRunner.ThenAsync(string.Format("parameter {0} on partial 0 should be {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Set TVF parameters")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set TVF parameters")]
        [global::Xunit.InlineDataAttribute("23", "80", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("24", "15", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("25", "10", "17", new string[0])]
        public async global::System.Threading.Tasks.Task SetTVFParameters(string paramNo, string value, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("paramNo", paramNo);
            argumentsOfScenario.Add("value", value);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set TVF parameters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 86
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 87
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 88
        await testRunner.WhenAsync(string.Format("I set parameter {0} on partial 0 to {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 89
        await testRunner.ThenAsync(string.Format("parameter {0} on partial 0 should be {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Set TVA parameters")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set TVA parameters")]
        [global::Xunit.InlineDataAttribute("41", "85", "18", new string[0])]
        [global::Xunit.InlineDataAttribute("42", "60", "19", new string[0])]
        [global::Xunit.InlineDataAttribute("43", "64", "20", new string[0])]
        public async global::System.Threading.Tasks.Task SetTVAParameters(string paramNo, string value, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("paramNo", paramNo);
            argumentsOfScenario.Add("value", value);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set TVA parameters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 97
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 98
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 99
        await testRunner.WhenAsync(string.Format("I set parameter {0} on partial 0 to {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 100
        await testRunner.ThenAsync(string.Format("parameter {0} on partial 0 should be {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Set waveform type")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set waveform type")]
        public async global::System.Threading.Tasks.Task SetWaveformType()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set waveform type", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 108
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 109
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 110
        await testRunner.WhenAsync("I set waveform on partial 0 to 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 111
        await testRunner.ThenAsync("waveform on partial 0 should be 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="All 58 partial parameters have valid defaults")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "All 58 partial parameters have valid defaults")]
        public async global::System.Threading.Tasks.Task All58PartialParametersHaveValidDefaults()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "22";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("All 58 partial parameters have valid defaults", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 113
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 114
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 115
        await testRunner.ThenAsync("all 58 parameters for partial 0 should have valid values", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Set pitch envelope parameters")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set pitch envelope parameters")]
        [global::Xunit.InlineDataAttribute("6", "80", "23", new string[0])]
        [global::Xunit.InlineDataAttribute("7", "5", "24", new string[0])]
        [global::Xunit.InlineDataAttribute("8", "5", "25", new string[0])]
        [global::Xunit.InlineDataAttribute("9", "70", "26", new string[0])]
        [global::Xunit.InlineDataAttribute("10", "3", "27", new string[0])]
        public async global::System.Threading.Tasks.Task SetPitchEnvelopeParameters(string paramNo, string value, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("paramNo", paramNo);
            argumentsOfScenario.Add("value", value);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set pitch envelope parameters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 117
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 118
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 119
        await testRunner.WhenAsync(string.Format("I set parameter {0} on partial 0 to {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 120
        await testRunner.ThenAsync(string.Format("parameter {0} on partial 0 should be {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Set pitch envelope time and level parameters")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set pitch envelope time and level parameters")]
        [global::Xunit.InlineDataAttribute("11", "50", "28", new string[0])]
        [global::Xunit.InlineDataAttribute("12", "60", "29", new string[0])]
        [global::Xunit.InlineDataAttribute("13", "70", "30", new string[0])]
        [global::Xunit.InlineDataAttribute("14", "80", "31", new string[0])]
        [global::Xunit.InlineDataAttribute("15", "40", "32", new string[0])]
        [global::Xunit.InlineDataAttribute("16", "30", "33", new string[0])]
        [global::Xunit.InlineDataAttribute("17", "20", "34", new string[0])]
        [global::Xunit.InlineDataAttribute("18", "45", "35", new string[0])]
        [global::Xunit.InlineDataAttribute("19", "35", "36", new string[0])]
        public async global::System.Threading.Tasks.Task SetPitchEnvelopeTimeAndLevelParameters(string paramNo, string value, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("paramNo", paramNo);
            argumentsOfScenario.Add("value", value);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set pitch envelope time and level parameters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 130
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 131
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 132
        await testRunner.WhenAsync(string.Format("I set parameter {0} on partial 0 to {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 133
        await testRunner.ThenAsync(string.Format("parameter {0} on partial 0 should be {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Set TVF bias and keyfollow parameters")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set TVF bias and keyfollow parameters")]
        [global::Xunit.InlineDataAttribute("26", "64", "37", new string[0])]
        [global::Xunit.InlineDataAttribute("27", "5", "38", new string[0])]
        [global::Xunit.InlineDataAttribute("28", "75", "39", new string[0])]
        [global::Xunit.InlineDataAttribute("29", "50", "40", new string[0])]
        [global::Xunit.InlineDataAttribute("30", "3", "41", new string[0])]
        [global::Xunit.InlineDataAttribute("31", "2", "42", new string[0])]
        public async global::System.Threading.Tasks.Task SetTVFBiasAndKeyfollowParameters(string paramNo, string value, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("paramNo", paramNo);
            argumentsOfScenario.Add("value", value);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set TVF bias and keyfollow parameters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 147
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 148
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 149
        await testRunner.WhenAsync(string.Format("I set parameter {0} on partial 0 to {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 150
        await testRunner.ThenAsync(string.Format("parameter {0} on partial 0 should be {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Set TVF envelope time and level parameters")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set TVF envelope time and level parameters")]
        [global::Xunit.InlineDataAttribute("32", "90", "43", new string[0])]
        [global::Xunit.InlineDataAttribute("33", "80", "44", new string[0])]
        [global::Xunit.InlineDataAttribute("34", "70", "45", new string[0])]
        [global::Xunit.InlineDataAttribute("35", "60", "46", new string[0])]
        [global::Xunit.InlineDataAttribute("36", "50", "47", new string[0])]
        [global::Xunit.InlineDataAttribute("37", "40", "48", new string[0])]
        [global::Xunit.InlineDataAttribute("38", "30", "49", new string[0])]
        [global::Xunit.InlineDataAttribute("39", "20", "50", new string[0])]
        [global::Xunit.InlineDataAttribute("40", "55", "51", new string[0])]
        public async global::System.Threading.Tasks.Task SetTVFEnvelopeTimeAndLevelParameters(string paramNo, string value, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("paramNo", paramNo);
            argumentsOfScenario.Add("value", value);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set TVF envelope time and level parameters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 161
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 162
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 163
        await testRunner.WhenAsync(string.Format("I set parameter {0} on partial 0 to {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 164
        await testRunner.ThenAsync(string.Format("parameter {0} on partial 0 should be {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Set TVA bias and envelope parameters")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set TVA bias and envelope parameters")]
        [global::Xunit.InlineDataAttribute("44", "-5", "52", new string[0])]
        [global::Xunit.InlineDataAttribute("45", "64", "53", new string[0])]
        [global::Xunit.InlineDataAttribute("46", "-4", "54", new string[0])]
        [global::Xunit.InlineDataAttribute("47", "3", "55", new string[0])]
        [global::Xunit.InlineDataAttribute("48", "2", "56", new string[0])]
        public async global::System.Threading.Tasks.Task SetTVABiasAndEnvelopeParameters(string paramNo, string value, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("paramNo", paramNo);
            argumentsOfScenario.Add("value", value);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set TVA bias and envelope parameters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 178
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 179
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 180
        await testRunner.WhenAsync(string.Format("I set parameter {0} on partial 0 to {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 181
        await testRunner.ThenAsync(string.Format("parameter {0} on partial 0 should be {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Set TVA envelope time and level parameters")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set TVA envelope time and level parameters")]
        [global::Xunit.InlineDataAttribute("49", "90", "57", new string[0])]
        [global::Xunit.InlineDataAttribute("50", "80", "58", new string[0])]
        [global::Xunit.InlineDataAttribute("51", "70", "59", new string[0])]
        [global::Xunit.InlineDataAttribute("52", "60", "60", new string[0])]
        [global::Xunit.InlineDataAttribute("53", "50", "61", new string[0])]
        [global::Xunit.InlineDataAttribute("54", "40", "62", new string[0])]
        [global::Xunit.InlineDataAttribute("55", "30", "63", new string[0])]
        [global::Xunit.InlineDataAttribute("56", "20", "64", new string[0])]
        [global::Xunit.InlineDataAttribute("57", "55", "65", new string[0])]
        public async global::System.Threading.Tasks.Task SetTVAEnvelopeTimeAndLevelParameters(string paramNo, string value, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("paramNo", paramNo);
            argumentsOfScenario.Add("value", value);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set TVA envelope time and level parameters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 191
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 192
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 193
        await testRunner.WhenAsync(string.Format("I set parameter {0} on partial 0 to {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 194
        await testRunner.ThenAsync(string.Format("parameter {0} on partial 0 should be {1}", paramNo, value), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Clone timbre preserves all parameters")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Clone timbre preserves all parameters")]
        public async global::System.Threading.Tasks.Task CloneTimbrePreservesAllParameters()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "66";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Clone timbre preserves all parameters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 208
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 209
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 210
        await testRunner.WhenAsync("I set the timbre name to \"Original\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 211
        await testRunner.AndAsync("I clone the timbre", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 212
        await testRunner.ThenAsync("the cloned timbre should have name starting with \"Original\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 213
        await testRunner.AndAsync("all parameters across all partials should match the original", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Timbre name is truncated to max 10 characters")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Timbre name is truncated to max 10 characters")]
        public async global::System.Threading.Tasks.Task TimbreNameIsTruncatedToMax10Characters()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "67";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Timbre name is truncated to max 10 characters", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 215
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 216
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 217
        await testRunner.WhenAsync("I set the timbre name to \"VeryLongTimbreName\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 218
        await testRunner.ThenAsync("the timbre name should start with \"VeryLongTi\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Set structure 3-4")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set structure 3-4")]
        public async global::System.Threading.Tasks.Task SetStructure3_4()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "68";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set structure 3-4", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 220
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 221
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 222
        await testRunner.WhenAsync("I set structure 3-4 to 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 223
        await testRunner.ThenAsync("structure 3-4 should be 8", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Set PCM sample parameter")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Set PCM sample parameter")]
        public async global::System.Threading.Tasks.Task SetPCMSampleParameter()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "69";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set PCM sample parameter", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 225
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 226
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 227
        await testRunner.WhenAsync("I set parameter 5 on partial 0 to 42", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 228
        await testRunner.ThenAsync("parameter 5 on partial 0 should be 42", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Mute all partials")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Mute all partials")]
        public async global::System.Threading.Tasks.Task MuteAllPartials()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "70";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Mute all partials", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 230
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 231
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 232
        await testRunner.WhenAsync("I mute partial 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 233
        await testRunner.AndAsync("I mute partial 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 234
        await testRunner.AndAsync("I mute partial 2", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 235
        await testRunner.AndAsync("I mute partial 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 236
        await testRunner.ThenAsync("all partials should be muted", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="PCM waveform disables TVF controls conceptually")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "PCM waveform disables TVF controls conceptually")]
        public async global::System.Threading.Tasks.Task PCMWaveformDisablesTVFControlsConceptually()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "71";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("PCM waveform disables TVF controls conceptually", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 238
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 239
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 240
        await testRunner.WhenAsync("I set waveform on partial 0 to 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 241
        await testRunner.ThenAsync("the waveform on partial 0 should be PCM", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 242
        await testRunner.AndAsync("TVF controls should be conceptually disabled for PCM", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="LA Synth waveform enables TVF controls")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "LA Synth waveform enables TVF controls")]
        public async global::System.Threading.Tasks.Task LASynthWaveformEnablesTVFControls()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "72";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("LA Synth waveform enables TVF controls", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 244
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 245
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 246
        await testRunner.WhenAsync("I set waveform on partial 0 to 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 247
        await testRunner.ThenAsync("the waveform on partial 0 should be LA Synth", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 248
        await testRunner.AndAsync("TVF controls should be enabled for LA Synth", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Switching from PCM to LA Synth re-enables TVF")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Switching from PCM to LA Synth re-enables TVF")]
        public async global::System.Threading.Tasks.Task SwitchingFromPCMToLASynthRe_EnablesTVF()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "73";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Switching from PCM to LA Synth re-enables TVF", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 250
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 251
        await testRunner.GivenAsync("a new timbre editor is opened", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 252
        await testRunner.WhenAsync("I set waveform on partial 0 to 1", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 253
        await testRunner.AndAsync("I set waveform on partial 0 to 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 254
        await testRunner.ThenAsync("TVF controls should be enabled for LA Synth", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Timbre undo restores previous state")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Timbre undo restores previous state")]
        public async global::System.Threading.Tasks.Task TimbreUndoRestoresPreviousState()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "74";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Timbre undo restores previous state", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 256
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 257
        await testRunner.GivenAsync("a new timbre editor is opened with history", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 258
        await testRunner.WhenAsync("I set the timbre name to \"BeforeUndo\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 259
        await testRunner.AndAsync("I record the change in history", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 260
        await testRunner.AndAsync("I set the timbre name to \"AfterChange\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 261
        await testRunner.AndAsync("I record the change in history", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 262
        await testRunner.AndAsync("I undo the last change", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 263
        await testRunner.ThenAsync("the timbre name should start with \"BeforeUndo\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Multiple undo and redo operations")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Timbre Editor")]
        [global::Xunit.TraitAttribute("Description", "Multiple undo and redo operations")]
        public async global::System.Threading.Tasks.Task MultipleUndoAndRedoOperations()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "75";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple undo and redo operations", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 265
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 266
        await testRunner.GivenAsync("a new timbre editor is opened with history", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 267
        await testRunner.WhenAsync("I set the timbre name to \"State1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 268
        await testRunner.AndAsync("I record the change in history", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 269
        await testRunner.AndAsync("I set the timbre name to \"State2\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 270
        await testRunner.AndAsync("I record the change in history", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 271
        await testRunner.AndAsync("I undo the last change", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 272
        await testRunner.AndAsync("I redo the last change", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 273
        await testRunner.ThenAsync("the timbre name should start with \"State2\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await TimbreEditorFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await TimbreEditorFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
